services:
  db:
    image: mariadb:latest
    container_name: demo-container
    restart: always
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - DEMO_PATH=${DEMO_PATH}
      - MARIADB_ROOT_PASSWORD=${ROOT_PASS}
    ports:
      # Map Host Port 3144 to Container Port 3306
      - "3144:3306"
    volumes:
      # Persists your data even if the container is deleted
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  go-app:
    build: .
    volumes:
      - ./uploads:/root/uploads
    environment:
      - DB_URL=${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:3306)/${DB_NAME}
    depends_on:
      - db
volumes:
  mariadb_data:
  