CREATE TABLE IF NOT EXISTS TEAMS (
    TEAMNAME VARCHAR(255) PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS MATCHES (
    MATCHID int AUTO_INCREMENT PRIMARY KEY ,
    DEMO_NAME varchar(255) NOT NULL ,
    MAP varchar(15) NOT NULL,
    SAVED_DATE varchar(10),
    PARSED_STATS BOOLEAN,
    PARSED_2D BOOLEAN,
    -- Team A Info
    TEAM_A_NAME VARCHAR(255),
    TEAM_A_T_SCORE INT DEFAULT 0,
    TEAM_A_CT_SCORE INT DEFAULT 0,
    TEAM_A_FINAL_SCORE INT DEFAULT 0,
    
    -- Team B Info
    TEAM_B_NAME VARCHAR(255),
    TEAM_B_T_SCORE INT DEFAULT 0,
    TEAM_B_CT_SCORE INT DEFAULT 0,
    TEAM_B_FINAL_SCORE INT DEFAULT 0,
    
    FOREIGN KEY (TEAM_A_NAME) REFERENCES TEAMS(TEAMNAME),
    FOREIGN KEY (TEAM_B_NAME) REFERENCES TEAMS(TEAMNAME)
);
CREATE TABLE IF NOT EXISTS ROUNDS (
    MATCHID INT NOT NULL,
    ROUND_NO INT NOT NULL,
    PRIMARY KEY (MATCHID, ROUND_NO), 
    CONSTRAINT FK_Match_Rounds 
        FOREIGN KEY (MATCHID) REFERENCES MATCHES(MATCHID) 
        ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS PLAYERS (
    PLAYERID BIGINT PRIMARY KEY,
    PLAYERNAME VARCHAR(100) NOT NULL UNIQUE,
    TEAMNAME VARCHAR(255),
    FOREIGN KEY (TEAMNAME) REFERENCES TEAMS(TEAMNAME) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS ROUND_PARTICIPANTS (
    MATCHID INT NOT NULL,
    ROUND_NO INT NOT NULL,
    PLAYERID BIGINT NOT NULL,
    SIDE INT,
    KILLS INT DEFAULT 0,
    DEATHS INT DEFAULT 0,
    PRIMARY KEY (MATCHID, ROUND_NO, PLAYERID),
    FOREIGN KEY (MATCHID, ROUND_NO) REFERENCES ROUNDS(MATCHID, ROUND_NO) ON DELETE CASCADE,
    FOREIGN KEY (PLAYERID) REFERENCES PLAYERS(PLAYERID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS ROUND_EVENTS (
    MATCHID INT NOT NULL,
    ROUND_NO INT NOT NULL,
    PLAYERID BIGINT NOT NULL,
    WEAPON VARCHAR(32),
    XPOS FLOAT,
    YPOS FLOAT,
    ZPOS FLOAT,
    TICK INT,
    PRIMARY KEY (MATCHID, ROUND_NO, PLAYERID, TICK),
    FOREIGN KEY (MATCHID, ROUND_NO, PLAYERID) REFERENCES ROUND_PARTICIPANTS(MATCHID, ROUND_NO, PLAYERID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS MATCH_STATS (
    MATCHID INT NOT NULL,
    PLAYERID BIGINT NOT NULL,
    TOTAL_KILLS INT DEFAULT 0,
    TOTAL_DEATHS INT DEFAULT 0,
    TOTAL_ASSISTS INT DEFAULT 0,
    PRIMARY KEY (MATCHID, PLAYERID),
    CONSTRAINT FK_Stats_Match FOREIGN KEY (MATCHID) 
        REFERENCES MATCHES(MATCHID) ON DELETE CASCADE,
    CONSTRAINT FK_Stats_Player FOREIGN KEY (PLAYERID) 
        REFERENCES PLAYERS(PLAYERID) ON DELETE CASCADE
);